"""
SafeLease AI - 마크다운/문서 리포트 생성기
"""

from datetime import datetime
from pathlib import Path
from core.analyzer.rules_engine import AnalysisResult
from core.analyzer.missing_checker import MissingCheckItem


def generate_markdown_report(analysis: AnalysisResult, missing_items: list[MissingCheckItem] = None) -> str:
    """분석 결과를 마크다운 형식의 보고서로 변환"""
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    score = analysis.safety_score
    status = "🟢 안전" if score >= 80 else ("🟡 주의" if score >= 50 else "🔴 위험")

    md = [
        f"# 🛡️ SafeLease AI 계약서 안심 진단 리포트",
        f"- **검토 일시**: {now}",
        f"- **대상 파일**: `{analysis.document_name}`",
        f"- **전체 조항 수**: {analysis.total_clauses}개",
        f"- **종합 안전 점수**: **{score}점 / 100점 ({status})**",
        f"- **위험도 현황**: 🔴 고위험 {analysis.risk_summary.get('RED', 0)}건 | 🟡 주의 {analysis.risk_summary.get('YELLOW', 0)}건",
        "",
        "---",
        "",
        "## 🚨 1. 주의가 필요한 불리한 특약 분석 & 협상 가이드",
        ""
    ]

    if not analysis.detected_issues:
        md.append("✅ **특이사항 없음**: 표준계약서 및 강행규정에 명백히 위배되는 불리한 특약이 발견되지 않았습니다.\n")
    else:
        for idx, iss in enumerate(analysis.detected_issues, 1):
            badge = "🔴 [조율 필요]" if iss.risk_level == "RED" else "🟡 [주의 권장]"
            md.extend([
                f"### {idx}. {badge} {iss.title} ({iss.page}페이지 • {iss.matched_clause_no or '특약'})",
                f"- **분류**: `{iss.category}`",
                f"- **계약서 원문 발췌 (제{iss.page}쪽)**: ",
                f"  > *\"{iss.verbatim_quote}\"*",
                f"- **⚠️ 사장님에게 불리한 이유**: {iss.danger_explanation}",
                f"- **📜 관련 법령/판례**: `{iss.legal_basis}`",
                f"- **✨ 추천 대체 조항 (계약서 수정용)**:",
                f"  ```text",
                f"  {iss.recommended_replacement}",
                f"  ```",
                f"- **💬 건물주 전송용 협상 문자/카톡 멘트**:",
                f"  > *\"{iss.nudge_script_polite}\"*",
                ""
            ])

    if missing_items:
        missing_list = [m for m in missing_items if m.is_missing]
        if missing_list:
            md.extend([
                "---",
                "",
                "## ⚠️ 2. 누락된 필수 보호 조항 체크리스트",
                "계약서에 적혀있지 않아 추후 분쟁이 생길 수 있는 항목입니다.",
                "",
                "| 점검 항목 | 누락 시 위험 | 추천 보완 문구 |",
                "| :--- | :--- | :--- |"
            ])
            for m in missing_list:
                md.append(f"| **{m.title}** | {m.why_important} | `{m.recommended_clause}` |")
            md.append("")

    md.extend([
        "---",
        "",
        "## ⚖️ 3. 법적 면책 고지 (Legal Disclaimer)",
        "* 본 리포트는 공인 표준계약서 및 법원 판례 DB와의 기계적 대조 분석 결과이며, **변호사법 제109조에 따른 법률적 대리나 개별 사안에 대한 확정적 법률 자문이 아닙니다.**",
        "* 실제 계약 체결 및 중대한 의사결정 시에는 반드시 변호사, 가맹거래사, 공인중개사 등 자격 있는 전문가의 확인을 받으시기 바랍니다.",
        "",
        "_Report generated by SafeLease AI_"
    ])

    return "\n".join(md)


def save_markdown_report(content: str, output_path: Path | str):
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
